{
 "title": "HNT Miner",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "CPU Core Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hnt_miner_cpu_temperature",
     "legendFormat": "{{exported_instance}}: core{{core}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hnt_miner_sync_status", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Online Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hnt_miner_online_status", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Relayed Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hnt_miner_relayed_status", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Height Gap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 0 },
   "targets": [
    { "expr": "hnt_miner_height_gap", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Miner / Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hnt_miner_miner_height", "legendFormat": "{{exported_instance}}" },
    { "expr": "hnt_miner_helium_block_height", "legendFormat": "blockchain" }
   ]
  },
  {
   "title": "Witnessed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hnt_miner_witnessed", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Witnesses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hnt_miner_witnesses", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Challenged Beacon 7d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_activity_challenged_beacon_7d",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Created Challenges 7d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_activity_create_challenge_7d",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Sent Beacon 7d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_activity_sent_beacon_7d",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Scale",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_scale", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Reward Earnings 1d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_earned_1d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Reward Earnings 7d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_earned_7d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Reward Earnings 30d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_earned_30d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Reward Counts 15m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hnt_miner_reward_15m", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Reward Earnings 15m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "targets": [
    { "expr": "hnt_miner_reward_earned_15m", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Counts 15m",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_15m", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Earnings 15m",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_earned_15m", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Reward Counts 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hnt_miner_reward_1h", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Reward Earnings 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "targets": [
    { "expr": "hnt_miner_reward_earned_1h", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Counts 1h",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_1h", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Earnings 1h",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_earned_1h", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Counts 1d",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hnt_miner_reward_1d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Reward Earnings 1d",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "targets": [
    { "expr": "hnt_miner_reward_earned_1d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Counts 1d",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_1d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Earnings 1d",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_earned_1d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Counts 7d",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hnt_miner_reward_7d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Reward Earnings 7d",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
   "targets": [
    { "expr": "hnt_miner_reward_earned_7d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Counts 7d",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_7d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Earnings 7d",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_earned_7d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Counts 30d",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hnt_miner_reward_30d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Earnings 30d",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hnt_miner_reward_earned_30d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Counts 30d",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_30d", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Rewards Earnings 30d",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hnt_miner_reward_earned_30d", "legendFormat": "{{exported_instance}}" }
   ]
  }
 ]
}