{
 "title": "HNT Miner",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Core Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_temperature",
     "legendFormat": "{{exported_instance}}: core{{core}}"
    }
   ]
  },
  {
   "title": "Miner Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_status",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Miner / Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_miner_height",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "bobcat_miner_helium_block_height",
     "legendFormat": "blockchain"
    }
   ]
  },
  {
   "title": "Height Gap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 2 },
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_height_gap",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Witnessed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_witnessed",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_witnessed",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Reward Scale",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_reward_scale",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_reward_scale",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Witnesses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_witnesses",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_witnesses",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Rewards (15 minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_reward_15m",
     "legendFormat": "{{exported_instance}}: rewards_15min"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_reward_15m",
     "legendFormat": "{{exported_instance}}: rewards_15min"
    }
   ]
  },
  {
   "title": "Rewards (1 hour)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_reward_1h",
     "legendFormat": "{{exported_instance}}: rewards_1hour"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_reward_1h",
     "legendFormat": "{{exported_instance}}: rewards_1hour"
    }
   ]
  },
  {
   "title": "Rewards (1 day)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_reward_1d",
     "legendFormat": "{{exported_instance}}: rewards_1day"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_reward_1d",
     "legendFormat": "{{exported_instance}}: rewards_1day"
    }
   ]
  },
  {
   "title": "Rewards (1 day)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_reward_1d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_reward_1d",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Rewards (7 days)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_reward_7d",
     "legendFormat": "{{exported_instance}}: rewards_7days"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_reward_7d",
     "legendFormat": "{{exported_instance}}: rewards_7days"
    }
   ]
  },
  {
   "title": "Rewards (7 day)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_reward_7d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_reward_7d",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Rewards (30 days)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_reward_30d",
     "legendFormat": "{{exported_instance}}: rewards_30days"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_reward_30d",
     "legendFormat": "{{exported_instance}}: rewards_30days"
    }
   ]
  },
  {
   "title": "Rewards (30 day)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bobcat_miner_custom_rusty_porcupine_reward_30d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "bobcat_miner_lively_clay_beetle_reward_30d",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}