{
 "title": "Helium Hotspots",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Relayed Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_relayed_status",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_relayed_status",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_relayed_status",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_relayed_status",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_relayed_status",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "P2P Inbound Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_dialable",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_dialable",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_dialable",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_dialable",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_dialable",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_sync_status",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_sync_status",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_sync_status",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_sync_status",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_sync_status",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "P2P Outbound Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_p2p_connected",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_p2p_connected",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_p2p_connected",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_p2p_connected",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_p2p_connected",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "IsHealthy? Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_is_healthy",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_is_healthy",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_is_healthy",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_is_healthy",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_is_healthy",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Witnessed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_witnessed",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_witnessed",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_witnessed",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_witnessed",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_witnessed ",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Height Gap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_height_gap",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_height_gap",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_height_gap",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_height_gap",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_height_gap",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Witnesses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_witnesses",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_witnesses",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_witnesses",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_witnesses",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_witnesses",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Rewards (1 hour)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_reward_1h",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_reward_1h",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_reward_1h",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_reward_1h",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_reward_1h",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Rewards (30 days)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_reward_30d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_reward_30d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_reward_30d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_reward_30d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_reward_30d",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Rewards (1 day)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_reward_1d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_reward_1d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_reward_1d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_reward_1d",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_reward_1d",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_cpu_temperature",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_cpu_temperature",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_cpu_temperature",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_cpu_temperature",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_cpu_temperature",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Reward Scale",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_reward_scale",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_reward_scale",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_reward_scale",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_reward_scale",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_reward_scale",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_cpu_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_cpu_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_cpu_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_cpu_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_cpu_used",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_memory_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_memory_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_memory_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_memory_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_memory_used",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "SD Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hnt_miner_dizzy_pecan_yeti_sd_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_radiant_red_mockingbird_sd_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_restless_lime_mole_sd_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_shaggy_parchment_crocodile_sd_used",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "hnt_miner_strong_magenta_swallow_sd_used",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}