#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.witnessed.count

witness() {
  log_info "processing data for ${a}"

  activity_types="get_activity_witnessed_beacons"

  activity_witnessed_beacon_15m=0
  activity_witnessed_beacon_1h=0
  activity_witnessed_beacon_1d=0
  activity_witnessed_beacon_7d=0
  activity_witnessed_beacon_30d=0

  for activity in ${activity_types}; do
    ${activity}
    get_activity_timestamps

    for t in ${activity_timestamps}; do
      time=${t}

      if [ "${minutes_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_witnessed_beacons" ]; then
          ((activity_witnessed_beacon_15m++)) || true
        fi
      fi

      if [ "${hour_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_witnessed_beacons" ]; then
          ((activity_witnessed_beacon_1h++)) || true
        fi
      fi

      if [ "${one_day_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_witnessed_beacons" ]; then
          ((activity_witnessed_beacon_1d++)) || true
        fi
      fi

      if [ "${seven_days_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_witnessed_beacons" ]; then
          ((activity_witnessed_beacon_7d++)) || true
        fi
      fi

      if [ "${thirty_days_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_witnessed_beacons" ]; then
          ((activity_witnessed_beacon_30d++)) || true
        fi
      fi
    done
  done

  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_witnessed_count || log_err "could not send [$id] data to prometheus gateway"
  done

  log_debug "hotspot witnessed count:  activity_witnessed_beacon_15m: ${activity_witnessed_beacon_15m} activity_witnessed_beacon_1h: ${activity_witnessed_beacon_1h} activity_witnessed_beacon_1d: ${activity_witnessed_beacon_1d} activity_witnessed_beacon_7d: ${activity_witnessed_beacon_7d} activity_witnessed_beacon_30d: ${activity_witnessed_beacon_30d}"

  rm_lock "${data_dir}/${client_id}/${a}/${lock_file}"
}


if [ "${hotspot_monitor}" == "true" ] && [ "${witness_count_etl}" == "true" ]; then
  minutes_ago=$(date -u --date="20 minutes ago" +%s)
  hour_ago=$(date -u --date="1 hour ago" +%s)
  one_day_ago=$(date -u --date="1 days ago" +%s)
  seven_days_ago=$(date -u --date="7 days ago" +%s)
  thirty_days_ago=$(date -u --date="30 days ago" +%s)
  lock_file=".${id}.lock"

  for address in ${addresses}; do
    addr=${address//*:/}
    addr=${addr//###/ }
    client_id=${address//:*/}

    get_prometheus_pg_host

    for a in ${addr}; do
      make_dir "${data_dir}/${client_id}/${a}"
      lock "${data_dir}/${client_id}/${a}/${lock_file}"

      get_activity_elasticsearch
      get_hotspot_name
      witness &
    done
  done
else
  log_debug "Hotspot monitor collection is disabled. Hint: (hotspot_monitor=${hotspot_monitor}; witness_count_etl=${witness_count_etl})" 
  true
fi
