#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.activity.count

activity_count() {
  log_info "processing data for ${a}"

  activity_types="get_activity_create_challenge get_activity_data_transfer"

  activity_create_challenge_15m=0
  activity_data_transfer_15m=0

  activity_create_challenge_1h=0
  activity_data_transfer_1h=0

  activity_create_challenge_1d=0
  activity_data_transfer_1d=0

  activity_create_challenge_7d=0
  activity_data_transfer_7d=0

  activity_create_challenge_30d=0
  activity_data_transfer_30d=0

  for activity in ${activity_types}; do
    ${activity}
    get_activity_timestamps

    for t in ${activity_timestamps}; do
      time=${t}

      if [ "${minutes_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_create_challenge" ]; then
          ((activity_create_challenge_15m++)) || true
        fi
  
        if [ "${activity}" == "get_activity_data_transfer" ]; then
          ((activity_data_transfer_15m++)) || true
        fi
      fi

      if [ "${hour_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_create_challenge" ]; then
          ((activity_create_challenge_1h++)) || true
        fi

        if [ "${activity}" == "get_activity_data_transfer" ]; then
          ((activity_data_transfer_1h++)) || true
        fi
      fi

      if [ "${one_day_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_create_challenge" ]; then
          ((activity_create_challenge_1d++)) || true
        fi

        if [ "${activity}" == "get_activity_data_transfer" ]; then
          ((activity_data_transfer_1d++)) || true
        fi
      fi

      if [ "${seven_days_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_create_challenge" ]; then
          ((activity_create_challenge_7d++)) || true
        fi

        if [ "${activity}" == "get_activity_data_transfer" ]; then
          ((activity_data_transfer_7d++)) || true
        fi
      fi

      if [ "${thirty_days_ago}" -le "${time}" ]; then
        if [ "${activity}" == "get_activity_create_challenge" ]; then
          ((activity_create_challenge_30d++)) || true
        fi

        if [ "${activity}" == "get_activity_data_transfer" ]; then
          ((activity_data_transfer_30d++)) || true
        fi
      fi
    done
  done

  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_activity_counts || log_err "could not send [$id] data to prometheus gateway"
  done

  log_debug "hotspot activity count:  activity_data_transfer_15m: ${activity_data_transfer_15m} activity_create_challenge_15m: ${activity_create_challenge_15m} activity_data_transfer_1h: ${activity_data_transfer_1h} activity_create_challenge_1h: ${activity_create_challenge_1h} activity_data_transfer_1d: ${activity_data_transfer_1d} activity_create_challenge_1d: ${activity_create_challenge_1d} activity_data_transfer_7d: ${activity_data_transfer_7d} activity_create_challenge_7d: ${activity_create_challenge_7d} activity_data_transfer_30d: ${activity_data_transfer_30d} activity_create_challenge_30d: ${activity_create_challenge_30d}"

  rm_lock "${data_dir}/${client_id}/${a}/${lock_file}"
}

if [ "${hotspot_monitor}" == "true" ] && [ "${activity_count_etl}" == "true" ]; then
  minutes_ago=$(date -u --date="20 minutes ago" +%s)
  hour_ago=$(date -u --date="1 hour ago" +%s)
  one_day_ago=$(date -u --date="1 days ago" +%s)
  seven_days_ago=$(date -u --date="7 days ago" +%s)
  thirty_days_ago=$(date -u --date="30 days ago" +%s)
  lock_file=".${id}.lock"

  for address in ${addresses}; do
    addr=${address//*:/}
    addr=${addr//###/ }
    client_id=${address//:*/}
 
    get_prometheus_pg_host

    for a in ${addr}; do
      make_dir "${data_dir}/${client_id}/${a}"
      lock "${data_dir}/${client_id}/${a}/${lock_file}"

      get_activity_elasticsearch
      get_hotspot_name
      activity_count
    done
  done
else
  log_debug "Hotspot monitor collection is disabled. Hint: (hotspot_monitor=${hotspot_monitor}; activity_count_etl=${activity_count_etl})"
  true
fi
