#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

get_addresses
minutes_ago=$(date -u --date="20 minutes ago" +%s)
hour_ago=$(date -u --date="1 hour ago" +%s)
one_day_ago=$(date -u --date="1 days ago" +%s)
seven_days_ago=$(date -u --date="7 days ago" +%s)
thirty_days_ago=$(date -u --date="30 days ago" +%s)
id=etl.activity.count

reward_count() {
  log_info "processing data for ${a}"

  activity_sent_beacon_15m=0
  activity_create_challenge_15m=0
  activity_challenged_beacon_15m=0
  activity_sent_beacon_1h=0
  activity_create_challenge_1h=0
  activity_challenged_beacon_1h=0
  activity_sent_beacon_1d=0
  activity_create_challenge_1d=0
  activity_challenged_beacon_1d=0
  activity_sent_beacon_7d=0
  activity_create_challenge_7d=0
  activity_challenged_beacon_7d=0
  activity_sent_beacon_30d=0
  activity_create_challenge_30d=0
  activity_challenged_beacon_30d=0

  get_activity_timestamps

  for t in ${activity}; do
    time=${t} 
    get_activity_data

    if [ "${minutes_ago}" -le "${time}" ]; then
      activity_sent_beacon_15m=$((activity_sent_beacon_15m + activity_sent_beacon))
      activity_create_challenge_15m=$((activity_create_challenge_15m + activity_create_challenge))
      activity_challenged_beacon_15m=$((activity_challenged_beacon_15m + activity_challenged_beacon))
    fi

    if [ "${hour_ago}" -le "${time}" ]; then
      activity_sent_beacon_1h=$((activity_sent_beacon_1h + activity_sent_beacon))
      activity_create_challenge_1h=$((activity_create_challenge_1h + activity_create_challenge))
      activity_challenged_beacon_1h=$((activity_challenged_beacon_1h + activity_challenged_beacon))
    fi

    if [ "${one_day_ago}" -le "${time}" ]; then
      activity_sent_beacon_1d=$((activity_sent_beacon_1d + activity_sent_beacon))
      activity_create_challenge_1d=$((activity_create_challenge_1d + activity_create_challenge))
      activity_challenged_beacon_1d=$((activity_challenged_beacon_1d + activity_challenged_beacon))
    fi

    if [ "${seven_days_ago}" -le "${time}" ]; then
      activity_sent_beacon_7d=$((activity_sent_beacon_7d + activity_sent_beacon))
      activity_create_challenge_7dm=$((activity_create_challenge_7d + activity_create_challenge))
      activity_challenged_beacon_7d=$((activity_challenged_beacon_7d + activity_challenged_beacon))
    fi

    if [ "${thirty_days_ago}" -le "${time}" ]; then
      activity_sent_beacon_30d=$((activity_sent_beacon_30d + activity_sent_beacon))
      activity_create_challenge_30d=$((activity_create_challenge_30d + activity_create_challenge))
      activity_challenged_beacon_30d=$((activity_challenged_beacon_30d + activity_challenged_beacon))
    fi
  done

  send_activity_counts

  log_debug "activity timestamps\n\n${activity}\n"
  log_debug "hotspot activity count:\n\n  activity_sent_beacon_15m: ${activity_sent_beacon_15m}\n  activity_create_challenge_15m: ${activity_create_challenge_15m}\n  activity_challenged_beacon_15m: ${activity_challenged_beacon_15m}\n  activity_sent_beacon_1h: ${activity_sent_beacon_1h}\n  activity_create_challenge_1h: ${activity_create_challenge_1h}\n  activity_challenged_beacon_1h: ${activity_challenged_beacon_1h}\n  activity_sent_beacon_1d: ${activity_sent_beacon_1d}\n  activity_create_challenge_1d: ${activity_create_challenge_1d}\n  activity_challenged_beacon_1d: ${activity_challenged_beacon_1d}\n  activity_sent_beacon_7d: ${activity_sent_beacon_7d}\n  activity_create_challenge_7d: ${activity_create_challenge_7d}\n  activity_challenged_beacon_7d: ${activity_challenged_beacon_7d}\n  activity_sent_beacon_30d: ${activity_sent_beacon_30d}\n  activity_create_challenge_30d: ${activity_create_challenge_30d}\n  activity_challenged_beacon_30d: ${activity_challenged_beacon_30d}\n"
}

if [ "${hotspot_monitor}" == "true" ]; then
  for a in ${addresses}; do
    get_hotspot_name
    reward_count
  done
else
  log_debug "Hotspot monitor collection is disabled. Hint: (hotspot_monitor=${hotspot_monitor})"
  true
fi
