#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.billing.balance
name=billing

wallet_data() {
  log_info "processing data for ${a}"

  get_billing_wallet_timestamps
  get_client_cost

  for t in ${billing_wallet_timestamps}; do
    days_elapsed=$(( ($(date --date @${now_epoch} +%s) - $(date --date @${t} +%s) )/(60*60*24) ))
    get_amount=$(jq -r --arg w "${a}" --argjson t "${t}" '.data[] | select(.time == $t) | select(.payer == $w) | .payments[].amount' <<< "${es_billing_wallet_payload}" | sort -u)

    amount=$((amount + get_amount)) || true
    days_total=$((days_total + days_elapsed)) || true
  done

  acc_cost=$(echo "scale=4; ${client_account_cost} / 30" | bc -l)
  amount=$(echo "${amount} * .00000001" | bc)
  modifier=$(echo "${days_total} * ${acc_cost}" | bc -l)
  billing_balance=$(echo "${amount} - ${modifier}" | bc -l)
  
  total_balance=$(echo "scale=4; ${total_balance} + ${billing_balance}" | bc -l)

  log_debug "billing balance: ${total_balance} days_elapsed: ${days_total}"
}

if [ "${wallet_etl_billing}" == "true" ]; then
  now_epoch=$(date +%s)
  get_addresses
  get_billing_wallet_elasticsearch

  for c in ${client_ids}; do
    client_id=${c}
    total_balance=0

    get_prometheus_pg_host

    for p in ${prometheus_pg_host}; do
      log_debug "pg_host = ${p}"

      if [[ "${p}" == *"hntmonitor.com"* ]] || [[ "${p}" == *"nginx-api"* ]]; then
        get_client_account
      else
        wallet_client_addresses=""
      fi

      for a in ${wallet_client_addresses}; do
        amount=0
        days_total=0
        wallet_data
      done

      if [ "${total_balance}" -le 0 ]; then
        total_balance=0
      fi

      payload="{ \"balance\": \"${total_balance}\" }"
      endpoint=balance
      if [[ "${p}" == *"hntmonitor.com"* ]]; then
        es_url=${p}
      else
        es_url=${elasticsearch_url}
      fi

      pghost=${p}
      send_billing_balance
      send_payload write "${data_dir}/${client_id}/${name}"
    done
  done
else
  log_debug "Wallet etl data is disabled. Hint: (wallet_etl_billing=${wallet_etl_billing})"
  true
fi
