#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.block.height

block_height() {
  log_info "processing data"

  get_height

  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_block_height
  done

  log_debug "hotspot block data:  block_height: ${height}"
}

if [ "${helium_monitor}" == "true" ] && [ "${block_height_etl}" == "true" ]; then
  if [[ ! "elasticsearch_url" == *"hntmonitor.com"* ]]; then
    name=helium
    block_height
  fi
else
  log_debug "Blocks monitor collection is disabled. Hint: (helium_monitor=${helium_monitor}; block_height_etl=${block_height_etl})"
  true
fi
