#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.longap
miner=longap

longap_data() {
  log_info "processing data"
  
  get_miner_longap_data
  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_miner_longap_data
  done

  log_debug "longap data:  block_height: ${block_height}  miner_height: ${miner_height}  sync_status: ${sync_status}  block_connected: ${block_connected}  height_gap: ${gap}"
}

if [ "${longap_monitor}" == "true" ]; then
  for address in ${longap_addresses}; do
    addr=${address//*:/}
    addr=${addr//###/ }
    client_id=${address//:*/}
 
    get_prometheus_pg_host

    for a in ${addr}; do
      get_miner_longap_name
      longap_data &
    done
  done
else
  log_debug "Longap monitor collection is disabled. Hint: (longap_monitor=${longap_monitor})"
  true
fi
