#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.bobcat

bobcat_temp() {
  id="${id}.temps"
  log_info "processing data"
  
  get_miner_bobcat_temp
  send_miner_bobcat_temp

  log_debug "Temperature data cpu0: ${temp0}; cpu1: ${temp1}"
}

bobcat_status() {
  id="${id}.status"
  log_info "processing data"

  get_miner_bobcat_status
  send_miner_bobcat_status

  log_debug "Status data \n  status: ${status}\n  gap: ${gap}\n  miner_height: ${miner_height}\n  block_height: ${blockchain_height}\n  epoch: ${epoch}\n"
}


if [ "${bobcat_monitor}" == "true" ]; then

  for a in ${bobcat_ips}; do
    get_miner_bobcat_name
    bobcat_temp &
    bobcat_status &
  done
else
  log_debug "Bobcat monitor collection is disabled. Hint: (bobcat_monitor=${bobcat_monitor})"
  true
fi
