#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.nebra
miner=nebra

nebra_data() {
  log_info "processing data"
  
  get_miner_nebra_data
  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_miner_nebra_data
  done

  log_debug "nebra data:  block_height: ${block_height}  miner_height: ${miner_height}  sync_status: ${sync_status}  frequency: ${frequency}  bluetooth_connected: ${bluetooth_connected}  lora_connected: ${lora_status}  miner_connected: ${miner_connected}  height_gap: ${gap}  sync_percent: ${sync_percent} response_time: ${miner_response_time}"
}

if [ "${nebra_monitor}" == "true" ]; then
  for address in ${nebra_ips}; do
    addr=${address//*:/}
    addr=${addr//###/ }
    client_id=${address//:*/}

    get_prometheus_pg_host

    for a in ${addr}; do
      get_miner_nebra_name
      nebra_data &
    done
  done
else
  log_debug "Nebra monitor collection is disabled. Hint: (nebra_monitor=${nebra_monitor})"
  true
fi
