#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.longap

longap_data() {
  log_info "processing data"
  
  get_miner_longap_data
  send_miner_longap_data

  log_debug "longap data:\n\n  block_height: ${block_height}\n  miner_height: ${miner_height}\n  sync_status: ${sync_status}\n  block_connected: ${block_connected}\n  height_gap: ${gap}\n"
}

if [ "${longap_monitor}" == "true" ]; then

  for a in ${longap_addresses}; do
    get_miner_longap_name
    longap_data &
  done
else
  log_debug "Longap monitor collection is disabled. Hint: (longap_monitor=${longap_monitor})"
  true
fi
