#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.sensecap

sensecap_data() {
  log_info "processing data"

  get_miner_sensecap_data
  send_miner_sensecap_data

  log_debug "sensecap data:\n\n  cpu_temperature: ${cputemp}\n  cpu_used: ${cpuused}\n  memory_total: ${memtotal}\n  memory_used: ${memused}\n  sd_total: ${sdtotal}\n  sd_used: ${sdused}\n  antenna_gain: ${gain}\n  relayed_status: ${relayed}\n  is_healthy: ${healthy}\n  block_height: ${totalheight}\n  miner_height: ${height}\n  p2p_connected: ${p2p_connected}\n  dialable_status: ${dialable}\n  nat_type: ${nattype}\n  height_gap: ${gap}\n"
}


if [ "${sensecap_monitor}" == "true" ]; then

  for a in ${sensecap_serial_numbers}; do
    get_miner_sensecap_name
    sensecap_data &
  done

else
  log_debug "Sensecap monitor collection is disabled. Hint: (sensecap_monitor=${sensecap_monitor})"
  true
fi
