#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.bobcat
miner=bobcat

bobcat_temp() {
  id="${id}.temps"
  log_info "processing data"
  
  get_miner_bobcat_temp
  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_miner_bobcat_temp
  done

  log_debug "${miner} temperature data:  cpu0: ${temp0}  cpu1: ${temp1}"
}

bobcat_status() {
  id="${id}.status"
  log_info "processing data"

  get_miner_bobcat_status
  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_miner_bobcat_status
  done

  log_debug "${miner} status data:  sync_status: ${sync_status}  height_gap: ${gap}  miner_height: ${miner_height}  block_height: ${block_height}  epoch: ${epoch}"
}

bobcat_latency() {
  id="${id}.latency"
  log_info "processing data"

  get_miner_response_time
  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_miner_response_time
  done

  log_debug "${miner} latecny data:  miner_response: ${miner_response_time}"
}

if [ "${bobcat_monitor}" == "true" ]; then
  get_addresses  

  for address in ${bobcat_ips}; do
    addr=${address//*:/}
    addr=${addr//###/ }
    client_id=${address//:*/}

    get_prometheus_pg_host

    for a in ${addr}; do
      get_miner_bobcat_name
      bobcat_temp &
      bobcat_status &
      bobcat_latency &
    done
  done
else
  log_debug "Bobcat monitor collection is disabled. Hint: (bobcat_monitor=${bobcat_monitor})"
  true
fi
