#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.online.status

online_status() {
  log_info "processing data for ${a}"

  get_online_status
  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_online_status
  done

  log_debug "hostspot online data:  online_status: ${online_status}"
}


if [ "${hotspot_monitor}" == "true" ] && [ "${online_status_etl}" == "true" ]; then
  get_addresses

  for address in ${addresses}; do
    addr=${address//*:/}
    addr=${addr//###/ }
    client_id=${address//:*/}

    get_prometheus_pg_host

    for a in ${addr}; do
      get_hotspot_name
      online_status &
    done
  done
else
  log_debug "Hotspot monitor collection is disabled. Hint: (hotspot_monitor=${hotspot_monitor}; online_status_etl=${online_status_etl})" 
  true
fi
