#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

get_addresses
id=etl.relayed.status

relayed_status() {
  log_info "processing data for ${a}"

  get_relayed_status
  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_relayed_status
  done

  log_debug "hostspot relayed data:\n\n  relayed_status: ${relayed_status}\n"
}


if [ "${hotspot_monitor}" == "true" ] && [ "${relayed_status_etl}" == "true" ]; then
  for a in ${addresses}; do
    get_hotspot_name
    relayed_status &
  done
else
  log_debug "Hotspot monitor collection is disabled. Hint: (hotspot_monitor=${hotspot_monitor}; relayed_status_etl=${relayed_status_etl})" 
  true
fi
