#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

get_addresses
id=etl.reward.scale

reward_scale() {
  log_info "processing data for ${a}"

  get_reward_scale
  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_reward_scale
  done

  log_debug "hotspot reward scale data:\n\n  reward_scale: ${scale}\n"
}

if [ "${hotspot_monitor}" == "true" ]; then
  for a in ${addresses}; do
    get_hotspot_name
    reward_scale
  done
else
  log_debug "Hotspot monitor collection is disabled. Hint: (hotspot_monitor=${hotspot_monitor})"
  true
fi
