#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

get_addresses
minutes_ago=$(date -u --date="20 minutes ago" +%s)
hour_ago=$(date -u --date="1 hour ago" +%s)
one_day_ago=$(date -u --date="1 days ago" +%s)
seven_days_ago=$(date -u --date="7 days ago" +%s)
thirty_days_ago=$(date -u --date="30 days ago" +%s)
id=etl.reward.count

reward_count() {
  log_info "processing data for ${a}"

  rewards_15m=0
  rewards_1h=0
  rewards_1d=0
  rewards_7d=0
  rewards_30d=0

  get_reward_timestamps

  for r in ${rewards}; do
    time=$(date -d ${r} +%s)    

    if [ "${minutes_ago}" -le "${time}" ]; then
      ((rewards_15m++)) || true
    fi

    if [ "${hour_ago}" -le "${time}" ]; then
      ((rewards_1h++)) || true
    fi

    if [ "${one_day_ago}" -le "${time}" ]; then
      ((rewards_1d++)) || true
    fi

    if [ "${seven_days_ago}" -le "${time}" ]; then
      ((rewards_7d++)) || true
    fi

    if [ "${thirty_days_ago}" -le "${time}" ]; then
      ((rewards_30d++)) || true
    fi
  done

  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_reward_counts
  done

  log_debug "rewards timestamps\n\n${rewards}\n"
  log_debug "hotspot reward count:\n\n  rewards_15m: ${rewards_15m}\n  rewards_1h: ${rewards_1h}\n  rewards_1d: ${rewards_1d}\n  rewards_7d: ${rewards_7d}\n  rewards_30d: ${rewards_30d}\n"
}

if [ "${hotspot_monitor}" == "true" ]; then
  for a in ${addresses}; do
    get_hotspot_name
    reward_count
  done
else
  log_debug "Hotspot monitor collection is disabled. Hint: (hotspot_monitor=${hotspot_monitor})"
  true
fi
