#!/usr/bin/env bash

set -euo pipefail

if [ ${trace} == "true" ]; then
  set -x
fi

id=etl.witness

witness() {
  log_info "processing data for ${a}"

  get_witness_count
  for p in ${prometheus_pg_host}; do
    pghost=${p}
    send_witness_count || log_err "could not send [$id] data to prometheus gateway"
  done

  log_debug "hostspot witness data:  witnesses_count: ${witnesses_count}  witnessed count: ${witnessed_count}"

  rm_lock "${data_dir}/${client_id}/${a}/${lock_file}"
}


if [ "${hotspot_monitor}" == "true" ] && [ "${witness_count_etl}" == "true" ]; then
  lock_file=".${id}.lock"
  get_addresses

  for address in ${addresses}; do
    addr=${address//*:/}
    addr=${addr//###/ }
    client_id=${address//:*/}

    get_prometheus_pg_host

    for a in ${addr}; do
      make_dir "${data_dir}/${client_id}/${a}"
      lock "${data_dir}/${client_id}/${a}/${lock_file}"

      get_hotspot_name
      witness &
    done
  done
else
  log_debug "Hotspot monitor collection is disabled. Hint: (hotspot_monitor=${hotspot_monitor}; witness_count_etl=${witness_count_etl})" 
  true
fi
