#!/usr/bin/env bash

set -euo pipefail

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd ${DIR}

for c in ../conf/*.conf; do
  . "${c}"
done

if [ ${debug} == "true" ]; then
  set -x
fi


addresses=$(< ../conf/address.list)
current_day=$(date +%Y-%m-%d -u)
current_time=$(date +%H:%M -u)
timestamp_30d=$(date +%Y-%m-%d -u --date="30 days ago")

get_miner() {
  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: getting hotspot data" >> "${logpath}/${logfile}"

  miner=$(curl -s https://${hotspot_url}/${a}) || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not retrieve miner data" >> "${logpath}/${logfile}"

  reward=$(curl -s https://${hotspot_url}/${a}/rewards?min_time=${timestamp_30d}) || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not retrieve reward data" >> "${logpath}/${logfile}"

  witnesses=$(curl -s https://${hotspot_url}/${a}/witnesses) || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not retrieve witnesses data" >> "${logpath}/${logfile}"
  witnessed=$(curl -s https://${hotspot_url}/${a}/witnessed) || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not retrieve witnessed data" >> "${logpath}/${logfile}"

  name=$(jq -r '.data.name' <<< "${miner}") || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not get the miner name" >> "${logpath}/${logfile}"

  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: hotspot data ready to process" >> "${logpath}/${logfile}"
}

reward_scale() {
  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: getting reward scale" >> "${logpath}/${logfile}"

  scale=$(jq -r '.data.reward_scale' <<< "${miner}") || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not retrieve reward scale" >> "${logpath}/${logfile}"

  cat <<EOF | curl --data-binary @- http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}
# HELP ${project}_reward_scale based on hex and nearby miners
# TYPE ${project}_reward_scale gauge
${project}_reward_scale{instance="${name}",address="${a}"} ${scale}
EOF
  
  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: reward scale pushed to http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}" >> "${logpath}/${logfile}"
}

reward_total() {
  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: getting reward data" >> "${logpath}/${logfile}"

  reward_cursor_30d=$(jq -r '.cursor' <<< "${reward}") || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not retrieve reward cursor" >> "${logpath}/${logfile}"
  reward_data=$(jq -r '.data[] | select(.timestamp != null) | .timestamp' <<< "${reward}") || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not retrieve reward data" >> "${logpath}/${logfile}"
  data=$(curl -s "https://${hotspot_url}/${a}/rewards?min_time=${timestamp_30d}&cursor=${reward_cursor_30d}" | jq '.') || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not retrieve data payload" >> "${logpath}/${logfile}"
  cursor=$(jq -r 'select(.cursor != null) | .cursor' <<< "${data}")
  rewards_15m=0
  rewards_1h=0
  rewards_1d=0
  rewards_7d=0
  rewards_30d=0

  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: reward data\n${reward}\n\n" >> "${logpath}/${logfile}"
  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: reward cursor ${reward_cursor_30d}" >> "${logpath}/${logfile}"
  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: cursor data\n${data}\n\n" >> "${logpath}/${logfile}"
  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: cursor data continue cursor ${cursor}" >> "${logpath}/${logfile}"

  while [ "${cursor}" ]; do
    new_data=$(curl -s "https://${hotspot_url}/${a}/rewards?min_time=${timestamp_30d}&cursor=${cursor}" | jq '.') || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not retrieve appended data" >> "${logpath}/${logfile}"
    cursor=$(jq -r 'select(.cursor != null) | .cursor' <<< "${new_data}")
    data="${data}
${new_data}"
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: appending cursor data\n${data}\n\n" >> "${logpath}/${logfile}"
  done

  rewards=$(jq -r '.data[].timestamp' <<< "${data}")
  hour=$(echo "${current_time}" | awk -F ':' '{print $1}')
  minute=$(echo "${current_time}" | awk -F ':' '{print $2}')

  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: rewards timestamps\n${rewards}\n\n" >> "${logpath}/${logfile}"
  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: captured UTC time ${hour}:${minute}" >> "${logpath}/${logfile}"

  for r in ${reward_data}; do
    clean_time=$(echo "${r}" | sed 's%.*T%%;s%\..*%%')
    h=$(echo "${clean_time}" | awk -F ':' '{print $1}')
    m=$(echo "${clean_time}" | awk -F ':' '{print $2}')
    m_loss=$((minute-16))
    rmh=${h}
    rmm=${m}

    if [ "${m_loss}" -lt "0" ]; then
      m_loss=$(echo "${m_loss}" | sed 's%-%%')
      m_loss=$((60-m_loss))
      rmh=${hour}
      rmm=${minute}
    fi
    
    if [ "${rmh}" -eq "${hour}" ] && [ "${rmm}" -le "${minute}" ] && [ "${m}" -ge "${m_loss}" ]; then
      ((rewards_15m++)) || true
    fi

    if [ "${h}" -eq "${hour}" ]; then
      ((rewards_1h++)) || true
    fi

    if [[ "${r}" == *"${current_day}"* ]]; then
      ((rewards_1d++)) || true
    fi

    ((rewards_7d++)) || true
    ((rewards_30d++)) || true
    rewards=$(echo "${rewards}" | sed "s%${r}%%")
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: verifying reward timestamp ${r}" >> "${logpath}/${logfile}"
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: cleaning up timestamp ${clean_time}" >> "${logpath}/${logfile}"
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: clean timestamp H(${h}) M(${m})" >> "${logpath}/${logfile}"
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: setting 15 minute maximum float ${m_loss}" >> "${logpath}/${logfile}"
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: minute data verification ${m} less than or equal to ${minute} and greater than or equal to ${m_loss}" >> "${logpath}/${logfile}"
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: hour data verification ${h} equals ${hour}" >> "${logpath}/${logfile}"
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: day data verification reward timestamp ${r} is in current day ${current_day}" >> "${logpath}/${logfile}"
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: removing ${r} from the rewards list" >> "${logpath}/${logfile}"
    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: remaining rewards timestamps\n${rewards}\n\n" >> "${logpath}/${logfile}"
  done

  rewards_1hour=$(echo "${rewards}" | grep "${current_day}" | sed 's%.*T%%;s%:.*%%' | grep "${hour}" | wc -l | tr -dc .[:print:]. || echo 0)
  rewards_1h=$((rewards_1h + rewards_1hour))

  rewards_1day=$(echo "${rewards}" | grep "${current_day}" | wc -l | tr -dc .[:print:]. || echo 0)
  rewards_1d=$((rewards_1d + rewards_1day))

  rewards_7day=$(echo "${rewards}" | grep "${current_day}\|$(date +%Y-%m-%d --date="1 day ago" -u)\|$(date +%Y-%m-%d --date="2 days ago" -u)\|$(date +%Y-%m-%d --date="3 days ago" -u)\|$(date +%Y-%m-%d --date="4 days ago" -u)\|$(date +%Y-%m-%d --date="5 days ago" -u)\|$(date +%Y-%m-%d --date="6 days ago" -u)\|$(date +%Y-%m-%d --date="7 days ago" -u)" | wc -l | tr -dc .[:print:]. || echo 0)
  rewards_7d=$((rewards_7d + rewards_7day))

  rewards_30day=$(echo "${rewards}" | wc -l | tr -dc .[:print:]. || echo 0)
  rewards_30d=$((rewards_30d + rewards_30day))

  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: rewards in 15 minute ${rewards_15m}" >> "${logpath}/${logfile}"
  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: rewards in 1 hour ${rewards_1h}" >> "${logpath}/${logfile}"
  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: rewards in 1 day ${rewards_1d}" >> "${logpath}/${logfile}"
  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: rewards in 7 days ${rewards_7d}" >> "${logpath}/${logfile}"
  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: rewards in 30 days ${rewards_30d}" >> "${logpath}/${logfile}"

  cat <<EOF | curl --data-binary @- http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}
# HELP ${project}_reward_15m total rewards by hour
# TYPE ${project}_reward_15m gauge
${project}_reward_15m{instance="${name}",address="${a}"} ${rewards_15m}
# HELP ${project}_reward_1h total rewards by hour
# TYPE ${project}_reward_1h gauge
${project}_reward_1h{instance="${name}",address="${a}"} ${rewards_1h}
# HELP ${project}_reward_1d total rewards in a day
# TYPE ${project}_reward_1d gauge
${project}_reward_1d{instance="${name}",address="${a}"} ${rewards_1d}
# HELP ${project}_reward_7d total rewards in 7 days
# TYPE ${project}_reward_7d gauge
${project}_reward_7d{instance="${name}",address="${a}"} ${rewards_7d}
# HELP ${project}_reward_30d total rewards in 30 days
# TYPE ${project}_reward_30d gauge
${project}_reward_30d{instance="${name}",address="${a}"} ${rewards_30d}
EOF

  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: reward data pushed to http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}" >> "${logpath}/${logfile}"
}

witness() {
  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: getting witness data" >> "${logpath}/${logfile}"
  witnessed_count=$(jq '.data[].name' <<< "${witnessed}" | wc -l)
  witnesses_count=$(jq '.data[].name' <<< "${witnesses}" | wc -l)

  cat <<EOF | curl --data-binary @- http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}
# HELP ${project}_witnessed miners
# TYPE ${project}_witnessed gauge
${project}_witnessed{instance="${name}",address="${a}"} ${witnessed_count}
# HELP ${project}_witnesses miners
# TYPE ${project}_witnesses gauge
${project}_witnesses{instance="${name}",address="${a}"} ${witnesses_count}
EOF
  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: witness data pushed to http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}" >> "${logpath}/${logfile}"
}


if [ "${hotspot_monitor}" == "true" ]; then
  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: Starting hotspot monitor run" >> "${logpath}/${logfile}"

  for a in ${addresses}; do
    echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: Gathering data for hotspot address - ${a}" >> "${logpath}/${logfile}"
    get_miner
    reward_scale &
    reward_total &
    witness &
    sleep 1
  done

  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: Hotspot monitor run complete" >> "${logpath}/${logfile}"
else
  [ "${debug}" == "true" ] && echo "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: Hotspot monitor collection is disabled. Skipping" >> "${logpath}/${logfile}"
fi
